M48
; DRILL file KiCad 10.0.1 date 2026-06-06T14:36:42
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-06T14:36:42-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X102.5Y-63.5
X102.5Y-123.5
X192.5Y-63.5
X192.5Y-123.5
T2
X120.0Y-64.07
M30
